### ISSUE TITLE
[Management] Releases

### ISSUE THREAD

**Issue by somehowchris** [rocket-org/Rocket#16]
**Existing Functionality**

A channel of communication with Sergio would be amazing. Since this didn't yet happen there needs to be some kind of backbone for releasing updates on this crate.

__Option A:__
Somehow get sergio on board and let him take part in releases. 
-> https://github.com/SergioBenitez/Rocket/discussions/2011#discussioncomment-1983130

__Option B:__
Release via github tags.
-> - Doesn't interfier with crates.io
-> - Doesn't work that well with dependabot and renovate
-> + Git is built into the cargo toolchain

__Option C:__
Release a new crate on crates.io
-> - This should be considered as a last option
-> - Confusion for developers
-> - If Sergio gets back on has to be marked as deprecated, crates on crates.io can't be deleted
-> + works fine with renovate and dependabot

**Comment by blackghost1987** [comment]
Option B is clearly not a good long term solution, but I really like it as a temporary solution! It could be a good compromise to have new releases as soon as the org wants, while also waiting for Sergio's response to ultimately decide between Option A or Option C.

This would also eliminate the problem under Option C: `If Sergio gets back on has to be marked as deprecated` - because the new crate would not be created unless Sergio's participation is already out of the question.

**Comment by somehowchris** [comment]
If we do any work regarding releases within the next weeks I would opt for B. 

Posted today in the matrix chat that we had a fork which will probably be moving and within seconds he responded 😊 He said he will be back from March on. Sadly (and historically) august turned into end-of-year, in october "will anounce soon" never arrived and getting that quick of a response seems like he's taking it personally (which intern means hes not doing that great from a psychological point of view)

**Comment by ittorchbearer** [comment]
I've been building a number of changes into a repo.  Many of them I'll be submitting ASAP after launch. Are you guys still trying to make rocket-org happen?

**Comment by somehowchris** [comment]
Not me, I have been trying to reach out to the owner of this org but no answer so far. Sergio actually has been back for some weeks and has been somewhat active.

If I might add some personal things: I’m actually changing from rocket to axum, and after my final exams I will be trying to create a high level, easy to use and scalable framework on top of axum which will have a lot of similarities to rocket but borrows a lot of concepts from nestjs, Django and spring boot @ramp-rs
