### ISSUE TITLE
[Feature] CI improvements

### ISSUE THREAD

**Issue by somehowchris** [rocket-org/Rocket#8]
**Is your feature request motivated by a concrete problem? Please describe.**

Todays ci pipelines only include native hardware as well as only `nightly` and `stable` build channels. To be sure that devs can go on and dev as well as run these we need to be sure to have support for the most common arch types. (not only x86)

**Why this feature can't or shouldn't live outside of Rocket**

CI is a central part of any project.

**Ideal Solution**

- Build and Test on x86 as well as common aarch64 (using cross)
- Build for msrv, stable, beta as well as nightly
- Use `actions-rs` with linting on check, fmt and clippy
- Use `actions-rs` with cargo-tarpaulin to generate codecov
- Use ci for doc generation
- Use ci for releases
- Use github deployments within ci

**Alternatives Considered**

**Additional Context**

Add any other context here, for example, descriptions of elegant solutions in other software.

**Comment by najtin** [comment]
> Use actions-rs with linting on check, fmt and clippy

If the PRs https://github.com/rocket-org/devise/pull/1 and https://github.com/rocket-org/figment/pull/3 go through, these actions are essential, at least on the respective projects.
